ingresses:
  - https://kabal-smart-editor-api.intern.nav.no
externalHosts:
springProfile: prod
db_tier: db-custom-1-3840
db_size: 10
db_ha: true
db_type: POSTGRES_15
tenant: nav.no

replicasMin: 2
replicasMax: 4

envs:
  - name: JAVA_OPTS
    value: "-Xms256m -Xmx2048m"